// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionCheckerController from "./accordion_checker_controller"
application.register("accordion-checker", AccordionCheckerController)

import ArtifactFormController from "./artifact_form_controller"
application.register("artifact-form", ArtifactFormController)

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import ContextMenuController from "./context_menu_controller"
application.register("context-menu", ContextMenuController)

import DatatableController from "./datatable_controller"
application.register("datatable", DatatableController)

import DraggableController from "./draggable_controller"
application.register("draggable", DraggableController)

import EpaReviewFormLogicController from "./epa_review_form_logic_controller"
application.register("epa-review-form-logic", EpaReviewFormLogicController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import FormSubmissionController from "./form_submission_controller"
application.register("form-submission", FormSubmissionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HighchartsController from "./highcharts_controller"
application.register("highcharts", HighchartsController)

import IdleTimeoutController from "./idle_timeout_controller"
application.register("idle-timeout", IdleTimeoutController)

import MeetingFiltersController from "./meeting_filters_controller"
application.register("meeting-filters", MeetingFiltersController)

import MeetingFormController from "./meeting_form_controller"
application.register("meeting-form", MeetingFormController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import SidePanelController from "./side_panel_controller"
application.register("side-panel", SidePanelController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)

import WindowController from "./window_controller"
application.register("window", WindowController)

import AccordionFiltersController from "./accordion_filters_controller"
application.register("accordion-filters", AccordionFiltersController)
