Rails.application.routes.draw do
  # get "searches/index"
  # get "searches/download_file"
  root "home#index"
  get "home/index"

  # resources :users do
  #   collection do
  #     get :search # if you want a specific search action
  #   end
  # end

  resources :searches do
    collection do
      get 'download_file'
    end
  end

  # Custom Login/Logout Routes
resource :session, only: [:new, :create, :destroy]

  # Passwords (Generated by Rails 8)
  resources :passwords, param: :token
end
