Rails.application.routes.draw do
  # get "searches/index"
  # get "searches/download_file"
  root "home#index"
  get "home/index"

  resources :searches do
    collection do
      get 'download_file'
    end
  end

  # Custom Login/Logout Routes
  get    "users/sign_in", to: "sessions#new",     as: :new_session
  post   "users/sign_in", to: "sessions#create",  as: :session
  delete "logout",        to: "sessions#destroy", as: :logout

  # Passwords (Generated by Rails 8)
  resources :passwords, param: :token
end
